name: ML
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=1.4.0
  - aiohttp=3.8.5
  - aiosignal=1.2.0
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=23.1.0
  - blas=1.0
  - blinker=1.6.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cachetools=4.2.2
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.6
  - cryptography=41.0.3
  - flatbuffers=2.0.0
  - frozenlist=1.3.3
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=2.22.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - h5py=3.9.0
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - jpeg=9e
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - libcurl=8.4.0
  - libffi=3.4.4
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - markdown=3.4.1
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - multidict=6.0.2
  - numpy=1.26.0
  - numpy-base=1.26.0
  - oauthlib=3.2.2
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - packaging=23.1
  - pip=23.2.1
  - protobuf=3.20.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-flatbuffers=2.0
  - re2=2022.04.01
  - requests=2.31.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.11.3
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.1.0
  - tk=8.6.12
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=2.2.3
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - wrapt=1.14.1
  - xz=5.4.2
  - yarl=1.8.1
  - zlib=1.2.13
  - pip:
      - opencv-python==4.8.1.78
